name: PI_and_CI
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - contourpy=1.3.1
  - cycler=0.12.1
  - fonttools=4.56.0
  - freetype=2.12.1
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libdeflate=1.23
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - munkres=1.0.7
  - ncurses=6.5
  - numpy=2.2.3
  - openjpeg=2.5.3
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pillow=11.1.0
  - pip=25.0.1
  - pthread-stubs=0.4
  - pyparsing=3.2.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytz=2024.1
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.2
  - six=1.17.0
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
